parameters:
#    sistema_sig_portal_web.example.class: SistemaSig\PortalWebBundle\Example

services:
#    sistema_sig_portal_web.example:
#        class: %sistema_sig_portal_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
