sistema_sig_news_homepage:
    pattern:  /
    defaults: { _controller: SistemaSigNewsBundle:News:index }

sistema_sig_news_create:
    pattern:  /crear
    defaults: { _controller: SistemaSigNewsBundle:News:create }
    requirements:
            _method:  GET|POST

sistema_sig_news_edit:
    pattern:  /editar/{newId}
    defaults: { _controller: SistemaSigNewsBundle:News:edit }
    requirements:
            _method:  GET|POST

sistema_sig_news_delete:
    pattern:  /eliminar/{newId}
    defaults: { _controller: SistemaSigNewsBundle:News:delete }
    requirements:
            _method:  GET|POST

sistema_sig_news_admin:
    pattern:  /admin
    defaults: { _controller: SistemaSigNewsBundle:News:admin }
    requirements:
            _method:  GET