sistema_sig_news_homepage:
    pattern:  /
    defaults: { _controller: SistemaSigNewsBundle:News:index }

sistema_sig_news_create:
    pattern:  /crear
    defaults: { _controller: SistemaSigNewsBundle:News:create }
    requirements:
            _method:  GET|POST