parameters:
#    sistema_sig_news.example.class: SistemaSig\NewsBundle\Example

services:
#    sistema_sig_news.example:
#        class: %sistema_sig_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
